In [1]:
from pandas import DataFrame

In [2]:
df = DataFrame({'거래처':['company1','company2','company3','company4','company5'],
                '주문량':[1500, 3040, 3389, 3343,1283],
                '할인율':[0.2,0.3,0.16,0.31,0.05]
                })
df

        거래처   주문량   할인율
0  company1  1500  0.20
1  company2  3040  0.30
2  company3  3389  0.16
3  company4  3343  0.31
4  company5  1283  0.05

In [ ]:
# 합계 : 문자는 나열
df.sum()

거래처    company1company2company3company4company5
주문량                                       12555
할인율                                        1.02
dtype: object

In [ ]:
# 누적합계
df.cumsum()

                                        거래처    주문량   할인율
0                                  company1   1500  0.20
1                          company1company2   4540  0.50
2                  company1company2company3   7929  0.66
3          company1company2company3company4  11272  0.97
4  company1company2company3company4company5  12555  1.02

In [6]:
# 나누기 -> 문자는 나누기 불가로 오류
# df.mean()

# numeric_only=True 옵션은 숫자만 평균 내기
df.mean(numeric_only=True)

주문량    2511.000
할인율       0.204
dtype: float64

In [ ]:
# 요약 정리
df.describe()

               주문량       할인율
count     5.000000  5.000000
mean   2511.000000  0.204000
std    1033.568333  0.107378
min    1283.000000  0.050000
25%    1500.000000  0.160000
50%    3040.000000  0.200000
75%    3343.000000  0.300000
max    3389.000000  0.310000

In [ ]:
df.sum(axis=1, numeric_only=True)
# df.sum(1, numeric_only=True)      axis 생략 가능

0    1500.20
1    3040.30
2    3389.16
3    3343.31
4    1283.05
dtype: float64

In [10]:
df1 = DataFrame({'거래처':['company1','company2','company3','company4','company5','company3','company2'],
                '주문량':[1500, 3040, 3389, 3343,1283,564, 442],
                '할인율':[0.2,0.3,0.16,0.31,0.05, 0.4,0.2]
                })
df1

        거래처   주문량   할인율
0  company1  1500  0.20
1  company2  3040  0.30
2  company3  3389  0.16
3  company4  3343  0.31
4  company5  1283  0.05
5  company3   564  0.40
6  company2   442  0.20

In [ ]:
# unique() : 중복 제거
df1.거래처.unique()

<StringArray>
['company1', 'company2', 'company3', 'company4', 'company5']
Length: 5, dtype: str

In [12]:
df1['거래처'].value_counts()

거래처
company2    2
company3    2
company1    1
company4    1
company5    1
Name: count, dtype: int64